from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from textwrap import dedent

import yaml


@dataclass(frozen=True)
class GeneratedRewardPaths:
    prompt_path: Path
    reward_module_path: Path


def load_reward_spec(spec_path: Path) -> dict:
    with spec_path.open("r", encoding="utf-8") as f:
        spec = yaml.safe_load(f)

    if not isinstance(spec, dict):
        raise ValueError(f"Reward spec at {spec_path} must be a YAML dictionary.")

    required_keys = [
        "name",
        "natural_language_objective",
        "available_state_variables",
        "reward_terms",
    ]

    missing = [key for key in required_keys if key not in spec]
    if missing:
        raise ValueError(f"Reward spec is missing required keys: {missing}")

    return spec


def build_reward_generation_prompt(spec: dict) -> str:
    objective = spec["natural_language_objective"]
    variables = "\n".join(f"- {v}" for v in spec["available_state_variables"])
    terms = "\n".join(
        f"- {key}: {value}" for key, value in spec["reward_terms"].items()
    )

    return dedent(
        f"""
        You are generating executable Python reward code for a robot recovery task.

        Natural-language objective:
        {objective}

        The recovery policy should bring the system back into a known-good state,
        not solve the original task goal directly.

        Available variables:
        {variables}

        Suggested reward term weights:
        {terms}

        Generate a Python function with this signature:

        def compute_language_reward(
            previous_distance_to_recovery: float,
            distance_to_recovery: float,
            action_norm: float,
            is_recovered: bool,
            is_out_of_bounds: bool,
        ) -> float:
            ...

        Requirements:
        - Reward progress toward the recovery zone.
        - Penalize remaining distance to the recovery zone.
        - Penalize large actions.
        - Add a success bonus when recovered.
        - Penalize leaving the valid workspace.
        - Return a plain Python float.
        """
    ).strip()


def build_reward_module_code(spec: dict) -> str:
    terms = spec["reward_terms"]

    distance_weight = float(terms["distance_weight"])
    progress_weight = float(terms["progress_weight"])
    success_bonus = float(terms["success_bonus"])
    action_penalty_weight = float(terms["action_penalty_weight"])
    out_of_bounds_penalty = float(terms["out_of_bounds_penalty"])

    objective = spec["natural_language_objective"].strip().replace('"""', '\\"\\"\\"')

    return dedent(
        f'''
        """
        Auto-generated language-shaped reward for Lang2Recover.

        Natural-language objective:
        {objective}

        This file is generated by scripts/07_generate_language_reward.py.
        Do not edit this file manually unless you intentionally want to override
        the generated reward.
        """

        from __future__ import annotations


        DISTANCE_WEIGHT = {distance_weight}
        PROGRESS_WEIGHT = {progress_weight}
        SUCCESS_BONUS = {success_bonus}
        ACTION_PENALTY_WEIGHT = {action_penalty_weight}
        OUT_OF_BOUNDS_PENALTY = {out_of_bounds_penalty}


        def compute_language_reward(
            previous_distance_to_recovery: float,
            distance_to_recovery: float,
            action_norm: float,
            is_recovered: bool,
            is_out_of_bounds: bool,
        ) -> float:
            """
            Reward for recovery-to-known-good-state.

            Positive behavior:
            - reduce distance to the recovery zone,
            - enter the recovery zone.

            Negative behavior:
            - remain far away,
            - use unnecessarily large actions,
            - leave the valid workspace.
            """
            progress = previous_distance_to_recovery - distance_to_recovery

            reward = 0.0
            reward += -DISTANCE_WEIGHT * distance_to_recovery
            reward += PROGRESS_WEIGHT * progress
            reward += -ACTION_PENALTY_WEIGHT * action_norm

            if is_recovered:
                reward += SUCCESS_BONUS

            if is_out_of_bounds:
                reward -= OUT_OF_BOUNDS_PENALTY

            return float(reward)
        '''
    ).strip() + "\n"


def generate_reward_from_spec(
    spec_path: Path,
    output_dir: Path,
) -> GeneratedRewardPaths:
    spec = load_reward_spec(spec_path)

    output_dir.mkdir(parents=True, exist_ok=True)

    prompt = build_reward_generation_prompt(spec)
    reward_code = build_reward_module_code(spec)

    prompt_path = output_dir / "cube_recovery_prompt.txt"
    reward_module_path = output_dir / "cube_recovery_language_reward.py"

    prompt_path.write_text(prompt + "\n", encoding="utf-8")
    reward_module_path.write_text(reward_code, encoding="utf-8")

    return GeneratedRewardPaths(
        prompt_path=prompt_path,
        reward_module_path=reward_module_path,
    )